name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.4.0
  device_info_plus: ^11.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  meta: ^1.17.0
  material_color_utilities: ^0.12.0
  vector_math: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png